export class Drink {
  constructor(
    public idDrink: string,
    public strDrink: string,
    public strCategory: string,
    public strAlcoholic: string,
    public strGlass: string,
    public strInstructions: string,
    public strDrinkThumb: string,
    public strIngredient1: string,
    public strIngredient2: string,
    public strIngredient3: string,
    public strIngredient4: string,
    public strIngredient5: string,
    public strIngredient6: string,
    public strIngredient7: string,
    public strIngredient8: string,
    public strIngredient9: string,
    public strIngredient10: string,
    public strIngredient11: string,
    public strIngredient12: string,
    public strIngredient13: string,
    public strIngredient14: string,
    public strIngredient15: string,
    public strMeasurement1: string,
    public strMeasurement2: string,
    public strMeasurement3: string,
    public strMeasurement4: string,
    public strMeasurement5: string,
    public strMeasurement6: string,
    public strMeasurement7: string,
    public strMeasurement8: string,
    public strMeasurement9: string,
    public strMeasurement10: string,
    public strMeasurement11: string,
    public strMeasurement12: string,
    public strMeasurement13: string,
    public strMeasurement14: string,
    public strMeasurement15: string,


  ) {}

  static adapt(item: any): Drink {
    return new Drink(
      item.idDrink,
      item.strDrink,
      item.strCategory,
      item.strAlcoholic,
      item.strGlass,
      item.strInstructions,
      item.strDrinkThumb,
      item.strIngredient1,
      item.strIngredient2,
      item.strIngredient3,
      item.strIngredient4,
      item.strIngredient5,
      item.strIngredient6,
      item.strIngredient7,
      item.strIngredient8,
      item.strIngredient9,
      item.strIngredient10,
      item.strIngredient11,
      item.strIngredient12,
      item.strIngredient13,
      item.strIngredient14,
      item.strIngredient15,
      item.strMeasure1,
      item.strMeasure2,
      item.strMeasure3,
      item.strMeasure4,
      item.strMeasure5,
      item.strMeasure6,
      item.strMeasure7,
      item.strMeasure8,
      item.strMeasure9,
      item.strMeasure10,
      item.strMeasure11,
      item.strMeasure12,
      item.strMeasure13,
      item.strMeasure14,
      item.strMeasure15,
    );
  }
}


//
